description: "<br> 14 <sup>th</sup> July 2023, Daegu, Korea<br/>"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Toward Natural Motion Generation (RSS 2023)"
github:
  is_project_page: false
