description: "RSS 2023 workshop <br/> 10 <sup>th</sup> <br/> or <br/>14 <sup>th</sup> July 2023 <br/> Daegu, Korea"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Toward Natural Motion Generation (RSS 2023)"
